### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by dellaert** [borglab/wrap#140]
I think the previous C++ wrapper *did* expose methods defined in wrapper superclasses. It makes little sense to me that I now have to repeat them in every derived class. I'm also thinking that some methods previously available might have simply *disappeared* because of this issue.

How hard is it to fix this?

Related question: is that why there is no `inference.i`? Many of the APIs are defined in inference, but we seem to have to repeat them now for Gaussian, Nonlinear, Discrete. A lot of work :-)

**Comment by dellaert** [comment]
@varunagrawal @ProfFan

**Comment by ProfFan** [comment]
I think Frank is correct here. *However* I guess because there is no Python unit test in GTSAM that uses this inherited superclasses, we may have overlooked.

**Comment by ProfFan** [comment]
On the fix. This is much harder now with multiple `.i` files, since we may need to look at other `.i`s for one file. If we limit inheritance to a single file, then this is pretty doable - we just do it like the way @varunagrawal added back overloads for MATLAB wrapper.

**Comment by varunagrawal** [comment]
There is a test fixture for inheritance in the wrapper so we should double check if methods are actually disappearing.

IIRC when I split the .i files, I simply cut and pasted stuff into various files based on grouping and some loose sense of clustering. I don't think I had to add duplicate methods at the time for subclasses, but this will need verification.

The fix is doable but needs a bit of an engineering effort. We need to first read in all the files, figure out all the inheritance dependencies, and then generate the pybind files for each file. This would need adding another class called `Module` or `File` representing each read file so we can write them out accordingly.

We'll need a week of no other work to figure this out. It's not hard but it is a time sink.

**Comment by varunagrawal** [comment]
@dellaert can you point me to an example of where methods are disappearing in subclasses?

**Comment by varunagrawal** [comment]
Okay I just checked something and this may change how we think about this issue.

`NoiseModelFactor` is defined in `nonlinear.i` and inherits from `NonlinearFactor` in the same file. Only `NonlinearFactor` defines methods such as `size`, `keys`, `active`, etc.

`RangeFactor2D` is defined in `sam.i`, so a different file, and has the following definition:
```cpp
template <POSE, POINT>
virtual class RangeFactor : gtsam::NoiseModelFactor {
  RangeFactor(size_t key1, size_t key2, double measured,
              const gtsam::noiseModel::Base* noiseModel);

  // enabling serialization functionality
  void serialize() const;
};
```
Note that it is very lean and only has 2 methods defined.

When I run this in an ipython terminal, it works

```python
f = gtsam.RangeFactor2D(0, 1, 1, gtsam.noiseModel.Isotropic.Sigma(1, 0.1))
f.print()
```

Looks like we're doing something wrong when writing the .i file?

**Comment by dellaert** [comment]
Aha, so it *does* work? It definitely *used* to work :-) I would also think that pybind11 would just know about inheritance without us having to do anything, but I'm not sure.

**Comment by varunagrawal** [comment]
It does work. And I thought the same thing about pybind11 since our bindings make it aware of the class inheritance.
We should look at your particular use case so we can figure why it isn't working there.

**Comment by dellaert** [comment]
I still have trouble, because I have to derive from a templated class (FactorGraph) in DiscreteFactorGraph. How can I do that?

**Comment by dellaert** [comment]
Seems it works.
